//CP TO DEMONSTRATE COMPILE-TIME INITIALIZATION
//HAYSTEN D'COSTA(21CO56)
#include<stdio.h>
//STRING HEADER FILE
#include<string.h>
void main()
{
    //DECLARATION AND [C-T] INITIALIZATION OF STRINNG
    char Name[20]="HAYSTEN D'COSTA";
    //OUTPUT OF STRING
    printf("%s",Name);
}

